// Auto-generated by tool/generate_instances_sm90.py
// Do not edit by hand.

#pragma once

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cstdint>

namespace ooverlap {

using PlainSm90FuncPtr = bool (*)(
    int M, int N, int K,
    half* A, half* B_col, half* D_col,
    cudaStream_t stream);

struct PlainSm90AlgoMeta {
  int tile_m;
  int tile_n;
  int tile_k;
  int cluster_m;
  int cluster_n;
  int cluster_k;
  int stages;
  const char* mainloop;
  const char* epilogue;
  const char* scheduler;
};

static PlainSm90FuncPtr plain_sm90_func_table[] = {
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<6>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedCooperative, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<6>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedCooperative, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 256, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedCooperative, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 256, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedCooperative, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<256, 128, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedCooperative, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<256, 128, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedCooperative, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<64, 256, 64, cutlass::gemm::collective::StageCount<5>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedPingpong, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<64, 256, 64, cutlass::gemm::collective::StageCount<5>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedPingpong, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<6>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedPingpong, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<7>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedPingpong, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<6>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedPingpong, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<7>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedPingpong, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<64, 256, 64, cutlass::gemm::collective::StageCount<5>, cute::Shape<cute::_1, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<64, 256, 64, cutlass::gemm::collective::StageCount<5>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<64, 256, 64, cutlass::gemm::collective::StageCount<5>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<7>, cute::Shape<cute::_1, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<7>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 128, 64, cutlass::gemm::collective::StageCount<7>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 256, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_1, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 256, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<128, 256, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<256, 128, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_1, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<256, 128, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_1, cute::_2, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
  &::cutlass_gemm_plain_sm90<256, 128, 64, cutlass::gemm::collective::StageCount<4>, cute::Shape<cute::_2, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto, void>,
};

static constexpr int plain_sm90_func_count = 24;

static PlainSm90AlgoMeta plain_sm90_algo_meta[] = {
  {128, 128, 64, 1, 2, 1, 6, "cooperative", "auto", "normal"},
  {128, 128, 64, 2, 1, 1, 6, "cooperative", "auto", "normal"},
  {128, 256, 64, 1, 2, 1, 4, "cooperative", "auto", "normal"},
  {128, 256, 64, 2, 1, 1, 4, "cooperative", "auto", "normal"},
  {256, 128, 64, 1, 2, 1, 4, "cooperative", "auto", "normal"},
  {256, 128, 64, 2, 1, 1, 4, "cooperative", "auto", "normal"},
  {64, 256, 64, 1, 2, 1, 5, "pingpong", "auto", "normal"},
  {64, 256, 64, 2, 1, 1, 5, "pingpong", "auto", "normal"},
  {128, 128, 64, 1, 2, 1, 6, "pingpong", "auto", "normal"},
  {128, 128, 64, 1, 2, 1, 7, "pingpong", "auto", "normal"},
  {128, 128, 64, 2, 1, 1, 6, "pingpong", "auto", "normal"},
  {128, 128, 64, 2, 1, 1, 7, "pingpong", "auto", "normal"},
  {64, 256, 64, 1, 1, 1, 5, "ws", "auto", "normal"},
  {64, 256, 64, 1, 2, 1, 5, "ws", "auto", "normal"},
  {64, 256, 64, 2, 1, 1, 5, "ws", "auto", "normal"},
  {128, 128, 64, 1, 1, 1, 7, "ws", "auto", "normal"},
  {128, 128, 64, 1, 2, 1, 7, "ws", "auto", "normal"},
  {128, 128, 64, 2, 1, 1, 7, "ws", "auto", "normal"},
  {128, 256, 64, 1, 1, 1, 4, "ws", "auto", "normal"},
  {128, 256, 64, 1, 2, 1, 4, "ws", "auto", "normal"},
  {128, 256, 64, 2, 1, 1, 4, "ws", "auto", "normal"},
  {256, 128, 64, 1, 1, 1, 4, "ws", "auto", "normal"},
  {256, 128, 64, 1, 2, 1, 4, "ws", "auto", "normal"},
  {256, 128, 64, 2, 1, 1, 4, "ws", "auto", "normal"},
};

} // namespace ooverlap
