// Auto-generated by tool/generate_instances_sm90.py
// Do not edit by hand.

#pragma once

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cstdint>

namespace ooverlap {

using SignalSm90FuncPtr = void (*)(
    int M, int N, int K,
    int ReLDN,
    int num_segments,
    int* CommThr,
    half* A, half* B, half* D,
    int* MM, int* RA,
    bool Monitor,
    cudaStream_t stream);

struct SignalSm90AlgoMeta {
  int tile_m;
  int tile_n;
  int tile_k;
  int cluster_m;
  int cluster_n;
  int cluster_k;
  const char* mainloop;
  const char* epilogue;
};

static SignalSm90FuncPtr signal_sm90_func_table[] = {
  &::cutlass_gemm_signal_sm90<128, 128, 32, cute::Shape<cute::_1, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto>,
  &::cutlass_gemm_signal_sm90<128, 128, 64, cute::Shape<cute::_1, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto>,
  &::cutlass_gemm_signal_sm90<128, 128, 128, cute::Shape<cute::_1, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecialized, cutlass::epilogue::collective::EpilogueScheduleAuto>,
};

static constexpr int signal_sm90_func_count = 3;

static SignalSm90AlgoMeta signal_sm90_algo_meta[] = {
  {128, 128, 32, 1, 1, 1, "ws", "auto"},
  {128, 128, 64, 1, 1, 1, "ws", "auto"},
  {128, 128, 128, 1, 1, 1, "ws", "auto"},
};

} // namespace ooverlap
